/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import net.datafaker.Faker
import java.util.*
import java.util.concurrent.Callable
import kotlin.time.measureTime


private const val INSTANCE_COUNT = 1_000_000

fun main() {
    // slow
    val faker = Faker(Locale.forLanguageTag("en-GB"))
//    // fast
//    val faker = Faker()

    val time = measureTime {
        for (i in 1..INSTANCE_COUNT) {
            faker.doWith(seed = i.toLong()) {
                println(faker.address().city())
            }
        }
    }
    println("Time to process $INSTANCE_COUNT values: $time")
}

